import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Robot <a href='https://nextjs.org'>RDK!</a>
        </h1>

        <hr></hr>

        <div>
          <h3> ROBOT Información: </h3>
          <form>
            <div className='grid'>
              <label>
                First name
                <input
                  type='text'
                  id='firstname'
                  name='firstname'
                  placeholder='Robot'
                  required
                />
              </label>

              <label>
                Last name
                <input
                  type='text'
                  id='lastname'
                  name='lastname'
                  placeholder='Last name'
                  required
                />
              </label>
            </div>

            <label>Email address</label>
            <input
              type='email'
              id='email'
              name='email'
              placeholder='Email address'
              required
            />
            <small> We ll never share your email with anyone else.</small>

            <button type='submit'>Submit</button>
          </form>
        </div>

        <div className={styles.grid}>
          <a href='https://nextjs.org/docs' className={styles.card}>
            <h2>Connect &rarr;</h2>
            <p>Realizar conexión al robot con IP entregada.</p>
          </a>

          <a href='https://nextjs.org/learn' className={styles.card}>
            <h2>Move test &rarr;</h2>
            <p>Realizar movimiento de prueba al robot con IP entregada.</p>
          </a>

          <a
            href='https://github.com/vercel/next.js/tree/canary/examples'
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          {/* Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span> */}
        </a>
      </footer>
    </div>
  );
};

export default Home;
